apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: "TCP"
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
